site_name: Iniciación a Python
site_description: Apuntes y actividades del curso de iniciación a Python

theme:
  name: mkdocs
  custom_dir: overrides

nav:
  - Inicio: index.md
  - Clase 1:
      - Variables y nomenclatura: clase1/01_variables_y_nomenclatura.md

extra_javascript:
  - assets/pwa.js