site_name: Taller de Programación I
site_description: Apuntes, actividades y recursos de la cursada de Taller de Programación I

theme:
  name: mkdocs
  custom_dir: overrides

nav:
  - Inicio: index.md
  - Programa de la materia: programa.md

  - Temas:
      - "Tema 0: Introducción a la programación": temas/tema00_introduccion.md

  - Clases:
      - "Clase 1: Presentación de la materia": clases/clase01/index.md
      - "Clase 2: Programas, lenguajes y algoritmos": clases/clase02/index.md
      - "Clase 3: Tipos, variables, expresiones y asignaciones": clases/clase03/01_variables_y_nomenclatura.md
      - "Clase 4: Cadenas de texto e inmutabilidad": clases/clase04/02_cadenas_e_inmutabilidad.md

extra_javascript:
  - assets/pwa.js